# Generated by Django 4.2.2 on 2023-08-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_location_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='short_github',
            new_name='social_github',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='short_linkedin',
            new_name='social_linkedin',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='short_twitter',
            new_name='social_twitter',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='short_website',
            new_name='social_website',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='short_youtube',
            new_name='social_youtube',
        ),
    ]
